# Generated by Django 3.2.7 on 2021-12-10 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pronto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.CharField(default='', max_length=255, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='time_entregue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='time_preparando',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='time_pronto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='time_realizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 8, 42, 43, 522014)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
