# Generated by Django 3.2.7 on 2021-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20211210_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Observações'),
        ),
    ]
