# Generated by Django 3.2.7 on 2021-12-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_observacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('preparar_pedido', 'Can preparar pedido'), ('entregar_pedido', 'Can entregar pedido')]},
        ),
    ]
